In [3]:
import numpy as np

i = 0

while i < 3:
    M = np.random.randint(-10, 11, size=(3, 3))
    i += 1
    print(M)
    if np.linalg.det(M) != 0:
        try:
            M_inv = np.linalg.inv(M)
            print(M_inv)
            identity_check = np.dot(M, M_inv)
            print(np.allclose(np.dot(M, M_inv), np.eye(3)))
        except np.linalg.LinAlgError:
            print("cannot inverse")

[[-8  4 -7]
 [ 0 -7 10]
 [-1 10 -2]]
[[-0.12338594 -0.08895265 -0.01291248]
 [-0.0143472   0.01291248  0.11477762]
 [-0.01004304  0.10903874  0.08034433]]
True
[[-5  6  2]
 [ 2  8 -8]
 [-6 -6  2]]
[[-0.06451613 -0.0483871  -0.12903226]
 [ 0.08870968  0.00403226 -0.07258065]
 [ 0.07258065 -0.13306452 -0.10483871]]
True
[[ -3   3 -10]
 [ -7   8  -1]
 [  5   6   3]]
[[ 0.03856041 -0.08868895  0.09897172]
 [ 0.02056555  0.05269923  0.08611825]
 [-0.10539846  0.04241645 -0.00385604]]
True
